version: '3.9'
services:  
  nginx:
    image: nginx:stable-alpine
    restart: always
    networks:
      - hackathon_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80

  backendserver:
    build:
      context: ./backend/server
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_BACK=${PORT_BACK}
    depends_on:
      - mysql
    networks:
      - hackathon_network
    volumes:
      - ./backend:/home/appuser/devcon
    expose:
      - ${PORT_BACK}
    # ports:
    #   - ${PORT_BACK}:${PORT_BACK}
    command: ["/bin/sh", "-c", "/home/appuser/devcon/backend.sh"]
  
  frontendserver:
    build:
      context: ./frontend/server
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_FRONT=${PORT_FRONT}
    env_file:
      - .env
    networks:
      - hackathon_network
    volumes:
      - ./frontend/server:/home/appuser/devcon
    expose:
      - ${PORT_FRONT}
    # ports:
    #   - ${PORT_FRONT}:${PORT_FRONT}
    command: ["/bin/sh", "-c", "npm start"]

  mysql:
    build:
      context: ./backend/mysql/
    networks:
      - hackathon_network
    volumes:
      - ./backend/mysql/data/db:/var/lib/mysql/ToDo_DB
    env_file:
      - .env
    # DB health check by sending ping with mysqladmin
    # DB ip:127.0.0.1
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD      
      interval: 10s      
      timeout: 10s      
      retries: 3
      start_period: 30s
  
  phpmyadmin:
    image: phpmyadmin:5.1-apache
    env_file:
      - .env
    links:
      - mysql
    networks:
      - hackathon_network
    ports:
      - ${PORT_PMA}:80
    volumes:
        - ./backend/phpmyadmin/sessions:/sessions

networks:
  hackathon_network:
